### ISSUE TITLE
Milestones are not aligned with quarter ticks

### ISSUE THREAD

**Issue by whizzzkid** [pln-planning-tools/Starmaps#100]
The milestones don't seem to align well:

![Screenshot 2022-11-15 at 11 45 28 AM](https://user-images.githubusercontent.com/1895906/202000732-a2fb072f-85ee-4cbe-908c-25ebdc4da05e.png)

![Screenshot 2022-11-15 at 11 45 35 AM](https://user-images.githubusercontent.com/1895906/202000752-d035b8f9-3362-4a48-bed1-e5b552ee97a3.png)

The reason this happens:
- We calculate the total number of ticks
- We calculate the start and end dates for the grid.
- We calculate grid intervals (quantiles) as: (end - start) / number of ticks
- Then for each milestone we align everything to the nearest grid interval, this nearest grid interval is not identical the ETAs on the milestone. This causes the milestones to be mis-aligned.

**Comment by SgtPooki** [comment]
@whizzzkid thanks so much for noticing and filing this. This is why I started the effort in the past to use d3 instead of a grid based representation, it just removes a lot of the complexity of time representation.. 

Do you have a fix in mind or specific topic you wanted to discuss for fixing this?

**Comment by whizzzkid** [comment]
@SgtPooki how best to do this, we can have quantiles set to days but that’s going to be super slow. I just feel the grid should not be equal i.e. the width should be pinned to quarter start stop dates. Otherwise things won’t align.

Using the alignment over the grid would be really hard and slow. I don't have an immediate fix.

**Comment by SgtPooki** [comment]
as we discussed after gui triage meeting, we need to do a deeper dive into the implementation details and granularity we need to support, which will have to be addressed after soft-launch EOD tomorrow.

- [ ] For now, we should use this action item to move the cards so that cards with dates "Q1'22" have their right side align with the "Q1'22" label, and each card's Quarter date should match with the label it's right side aligns with.

Also, for now, we can limit the visibility of quarters to being a sequential range of 2-6 quarters, as that was the original vision in the google doc with Molly. If this takes significantly more work, I don't think we should take  this on prior to Wednesday, but could as a P1 item.
