### ISSUE TITLE
feat: block mobile with pleasant UX until we support mobile

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/StarMaps#136]
Currently, the mobile experience is not ideal. In a perfect world, this app would have been mobile-first, but the main use-case we targeted was roadmap screenshots for presentations. Because of that, mobile was a secondary concern and is now an unpleasant, "don't even try it" experience. 

We should enhance that experience by creating a landing page that at least lets users know we're aware of this experience, and link to a tracking issue for mobile support.

**Comment by SgtPooki** [comment]
@juliaxbow when you get a chance, it could be a good idea to throw some mobile landing/blocking page together

I'm thinking of redirecting to a full page display that says something like "Mobile not supported at this time. Follow [issue link] for updates!"

**Comment by juliaxbow** [comment]
will get something together today!

**Comment by SgtPooki** [comment]
Note that if we have some layouts defined for different breakpoints, it may make styling a little easier. chakra-ui breakpoints defined at https://chakra-ui.com/docs/styled-system/responsive-styles

```js
// These are the default breakpoints
const breakpoints = {
  sm: '30em',
  md: '48em',
  lg: '62em',
  xl: '80em',
  '2xl': '96em',
}
```

**Comment by AlexxNica** [comment]
The first version was developed with responsiveness in mind, for desktop and mobile use. It seems this bug was introduced by recent changes.

We can check this by comparing the first version to the latest one:
- MapLight version: https://maplight.vercel.app/roadmap/github.com/ipfs/roadmap/issues/102?view=detail
- Latest version: https://www.starmaps.app/roadmap/github.com/ipfs/roadmap/issues/102

MapLight:
![image](https://user-images.githubusercontent.com/14338588/202787776-fdd0ec5a-87d6-47b4-9910-ff2bfe03d626.png)

Latest:
![image](https://user-images.githubusercontent.com/14338588/202787898-557f4ac3-09d0-4141-985d-c812c84769f8.png)

I advise using CSS grid's native responsiveness features to automatically adapt to mobile, as done in the MapLight version. Let me know if you need any assistance!!

**Comment by juliaxbow** [comment]
Sorry - missed this one. I'm +1 to native responsiveness, of course, but in the interim we could do something like the below. Rather than a screen fully preventing the use of starmaps in mobile, suggesting a pop-up warning. 

Header: 18pt, Medium weight; #FFFFFF
P1: 16pt, Regular weight; #D7D7D7
Button text: 18pt, Regular, #1FA5FF
Pop-up Fill: #27292C
Pop-up Highlight Line: F39106

![Image](https://user-images.githubusercontent.com/58958327/204595374-91c6b2db-464d-455e-8265-bd4a2998e61e.png)

**Comment by juliaxbow** [comment]
Shared via slack - will start an icons folder in this repo, too
[Roadmapping Tool MVP (2).zip](https://github.com/pln-planning-tools/StarMaps/files/10127368/Roadmapping.Tool.MVP.2.zip)
