### ISSUE TITLE
Milestone label is not being required on issues

### ISSUE THREAD

**Issue by wilkyr31d** [pln-planning-tools/Starmaps#37]
Milestone label should be required on root issues

- [ ] As Root? (yes)
- [ ] As child? (no...? @wilkyr31d to clarify)

If a milestone label is not on a github issue whose URL is provided in the tool, we need to display an error.. What should that error say?

**Comment by wilkyr31d** [comment]
I'm wondering at this point if there's value in requiring the milestone label at all. When I was adding roadmaps it did cross my mind that it seemed unnecessary. It may be a good practice to make data entry saner, but it's not strictly needed by the tool I think. 

@juliaxbow what do you think?

**Comment by juliaxbow** [comment]
>If a milestone label is not on a github issue whose URL is provided in the tool, we need to display an error.. What should that error say?

Agreed that if _any_ link is entered that does not follow the correct format (or whatever is prescribed), we should have an error message. 

>I'm wondering at this point if there's value in requiring the milestone label at all. When I was adding roadmaps it did cross my mind that it seemed unnecessary. It may be a good practice to make data entry saner, but it's not strictly needed by the tool I think.


@wilkyr31d If I'm understanding your latest comment, though, we're considering requiring a "Milestone" label in order to be used with the tool, which may or may not be necessary to actually use the tool.

If my understanding of the above is correct, I am in favor of requiring the Milestone label even if it is not technically required to use the tool. Reasons being:
- Requiring a milestone label or some sort of marker is a pretty minor ask and will allow for consistent data entry
- A milestone label can be added in after the fact by the roadmap creator or some other maintainer if it was accidentally omitted 
- Including a milestone tag will allow users (anyone looking to view a team roadmap) to know what they can or can't paste into and view with the starmaps tool. I assume we'll have a simple database somewhere of all github roadmap links but we'll also run into users who find the starmaps tool separately

The only real drawback I see is that whoever is creating the roadmapping tool will have one addt'l requirement. But the benefits outweigh this cost IMO

**Comment by wilkyr31d** [comment]
Dup of https://github.com/pln-planning-tools/Starmaps/issues/51
