### ISSUE TITLE
feat: add error collection notification functionality

### ISSUE THREAD

**Issue by SgtPooki** [pln-planning-tools/Starmaps#96]
![image](https://user-images.githubusercontent.com/1173416/201836318-3f6e181a-89b1-4630-b249-b450d926fe43.png)

Spawned off of https://github.com/pln-planning-tools/Starmaps/issues/51 and specifically the mockup by @juliaxbow at https://github.com/pln-planning-tools/Starmaps/issues/51#issuecomment-1312289169

leaving this item without P0 or P1 for now because I feel like we need to nail down the exact functionality and mock.

1. The mockups provided by Julia show the error notifications at the top. I think we should render them towards the bottom, or collapsed as recommended by Reid. We need to solidify this UX
2. The error content seems to be straightforward, but I want us to map it out exactly
    * What are the error cases we want to support?
    * Do we want to collect errors as they occur, or have this notification box only collect errors that occur with rendering the specific URL entered and its children? **(I vote for the latter.)**
    * Do we only need issue URL (root or child) and description of error? **(I vote yes)**
    * What is the n->m mapping for issueUrls, line items, errors, and error descriptions?
        *  is each item in the box only related to a single url? **(I vote yes)**
        * Is each URL related to only a single error? **(I vote no. We should split errors by semi-colon as seen in the screenshots first item)**
        * Do we have a maximum number of errors to display? what do we want to do if a certain issueURL surpasses that max? **(I vote we handle later if&when necessary)**
             * Do we even need to worry about maximum issues or if there are categories of different errors do we want to collect them? (invalid URL, vs schema, vs label, vs others covered in #51?)  **(I vote we handle later if&when necessary)**

Note that we do not need to nail down all potential error cases, but we should have a clear definition of scope for this task and what we want to handle, and move forward from there. 

@whizzzkid @juliaxbow looking for your input. Not trying to solve the world, but trying to make sure edge-cases are thought of so we don't build something challenging to update for the future.

**Comment by juliaxbow** [comment]
1. Reid and I had discussed placing the error log at the top, after I had originally suggested having a popup within the window, so that the errors don't go unnoticed and the user knows they are getting an incomplete view of the roadmap. I agree this should be collapsible, though. Instead of allowing the user to exit (X icon) we should instead have a collapse icon (down to up "V" arrow). That also prevents accidental closing of the error log.
2. WRT error mapping:
- I'll link the possible errors and related actions once I have them all mapped out. Adding in the next hour or so and will edit this comment
- +1 to only including issue URL and description of error (standardized) in the error log
- +1 to listing all errors associated with each URL
- I don't think we should set a max number of errors right now. Once we have more roadmaps to play around with we'll get a better sense as to what this will look like. If that means we have a way-too-long error log for the time being, I'm OK with that. 
- > is each item in the box only related to a single url? (I vote yes) 
- not sure I understand if you don't mind elaborating. If this means "should each error only be attached to a single URL?" (vs, for example, "No ETA Error: URL1, URL2, URL3" then yes

**Comment by whizzzkid** [comment]
I mostly agree with what @juliaxbow posted ☝🏽, also:
- We should limit the maximum number of errors to say 5 and have ellipses `... and NNN more errors`, because if there are plenty of children and they made a mistake, we would just have a giant wall of errors.
- We should classify the errors and point them to the relevant section of the guide.
    - ETA Missing: Eta section
    - Bad Content: format section
    - All other error: Please follow the guide.
- Also, I think it may not be worth it to parse all URLs just to give users waiting for the roadmap to render an error message. e.g. If their roadmap has 10 children x 10 grandchildren each, we can be spending a huge time to parse those. We should either make it async, or fail fast so that the user can fix the issue and retry instead of waiting for the list of all faulty URLs.

**Comment by SgtPooki** [comment]
> not sure I understand if you don't mind elaborating. If this means "should each error only be attached to a single URL?" (vs, for example, "No ETA Error: URL1, URL2, URL3" then yes

Yes, we're on the same page

> I do think we should have an "unknown error" message in addition to defined errors since unknown errors are (i think) inevitable and it's better to at least indicate that something went wrong at the expense of a user's frustration of not knowing what than it is to omit any indication that something went wrong

100% agree. 

> I think it may not be worth it to parse all URLs just to give users waiting for the roadmap to render an error message. e.g. If their roadmap has 10 children x 10 grandchildren each, we can be spending a huge time to parse those. We should either make it async, or fail fast so that the user can fix the issue and retry instead of waiting for the list of all faulty URLs.

I agree with making things more async. I would love the first return after URL submission to happen immediately, and then the processing of children populate async. This is probably a P2 or post-MVP level of work though. 

> We should limit the maximum number of errors to say 5 and have ellipses ... and NNN more errors, because if there are plenty of children and they made a mistake, we would just have a giant wall of errors.

I'm fine with an artificial error cap for now! Easy to implement and change either way. @juliaxbow are you good with this? It would also make it easy for them to target the known errors and then re-render to get more as they solve issues.

> We should classify the errors and point them to the relevant section of the guide.

100%! I propose the following Error object:

```typescript
interface StarMapsError {
  /**
   * The GitHub html_url for the issue with the error.
   */
  url: string;
  /**
   * The URL to the relevant section in the User Guide.md
   * Link to overall user-guide if error is not relevant to a specific section
   */
  userGuideUrl: string;
  /**
   * Friendly error title
   */
  title: string;
  /**
   * Descriptive error message
   */
  message: string;
}
```

**Comment by SgtPooki** [comment]
it sounds like we may have enough information to proceed here, so I'm marking this as P0 and status/ready

**Comment by SgtPooki** [comment]
errors are being mapped out at https://www.notion.so/pl-strflt/6f954228b20f4a2c81bc04900fe1b4d9?v=1242b090607a4c0cb97f92c3e060a3b6

**Comment by juliaxbow** [comment]
Noted on the error cap; will add another error message into the table in notion. 

Also here's what I'm thinking for the collapsible error log (please feel free to edit any content if my terms are used incorrectly, e.g. "render":

https://user-images.githubusercontent.com/58958327/202009869-29e9ec32-d912-43ee-8d3c-3679d24ddb38.mov
